apiVersion: v1
kind: 

metadata:
  name: nginx-service
  labels:
    app: nginx

spec:
  selector:
    app: nginx
  type: ClusterIP
  ports:
  - name: nginx-service
    port: 80
    targetPort: 80
    protocol: tcp